name: kanji_no_ryoushi
description: 'A new Flutter project for OCR using ML Kit.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # iOS style icons
  cupertino_icons: ^1.0.8

  # OCR
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_commons: ^0.11.0
  # Language identification for detecting language codes reliably
  google_mlkit_language_id: ^0.13.0
  image_picker: ^1.2.0

  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  # Image manipulation (crop/encode) in pure Dart
  image: ^4.0.17
  # HTTP client for downloading dictionary
  http: ^1.1.0
  # Zip/tar archive handling
  archive: ^3.3.0
  sqflite: ^2.2.8
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/prueba_texto.png
    - assets/images/icon.jpg

# Configuración del ícono de la app
flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/images/icon.jpg'
  min_sdk_android: 21
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: 'assets/images/icon.jpg'
